class Solution {
        public List<String> removeInvalidParentheses(String s) {
                int remL = 0, remR = 0;
                        
                                // Count minimum removals needed
                                        for (int i = 0; i < s.length(); i++) {
                                                    char c = s.charAt(i);
                                                                if (c == '(') {
                                                                                remL++;
                                                                                            } else if (c == ')') {
                                                                                                            if (remL > 0) {
                                                                                                                                remL--;
                                                                                                                                                } else {
                                                                                                                                                                    remR++;
                                                                                                                                                                                    }
                                                                                                                                                                                                }
                                                                                                                                                                                                        }
                                                                                                                                                                                                                
                                                                                                                                                                                                                        Set<String> res = new HashSet<>();
                                                                                                                                                                                                                                dfs(s, 0, 0, remL, remR, new StringBuilder(), res);
                                                                                                                                                                                                                                        return new ArrayList<>(res);
                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                    private void dfs(String s, int idx, int open, int remL, int remR, StringBuilder cur, Set<String> res) {
                                                                                                                                                                                                                                                            if (open < 0) return;
                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                            if (idx == s.length()) {
                                                                                                                                                                                                                                                                                        if (remL == 0 && remR == 0 && open == 0) {
                                                                                                                                                                                                                                                                                                        res.add(cur.toString());
                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                return;
                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                        char c = s.charAt(idx);
                                                                                                                                                                                                                                                                                                                                                                int len = cur.length();
                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                // Option 1: Remove the current bracket
                                                                                                                                                                                                                                                                                                                                                                                        if (c == '(' && remL > 0) {
                                                                                                                                                                                                                                                                                                                                                                                                    dfs(s, idx + 1, open, remL - 1, remR, cur, res);
                                                                                                                                                                                                                                                                                                                                                                                                            } else if (c == ')' && remR > 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                        dfs(s, idx + 1, open, remL, remR - 1, cur, res);
                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                // Option 2: Keep the current character
                                                                                                                                                                                                                                                                                                                                                                                                                                                        cur.append(c);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (c == '(') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            dfs(s, idx + 1, open + 1, remL, remR, cur, res);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } else if (c == ')') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                dfs(s, idx + 1, open - 1, remL, remR, cur, res);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    dfs(s, idx + 1, open, remL, remR, cur, res);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    cur.setLength(len);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
